- name: Create directories
  file:
    path: "{{huginn_hostdir}}/{{ item.path }}"
    state: directory
    mode: '{{ item.mode }}'
  with_filetree: "{{huginn_code_dir}}/setup/"
  when: item.state == 'directory'
- name: Template files
  template:
    src: '{{ item.src }}'
    dest: "{{huginn_hostdir}}/{{ item.path }}"
    mode: '{{ item.mode }}'
    trim_blocks: false
  with_filetree: "{{huginn_code_dir}}/setup/"
  when:
  - "item.state == 'file'"
  - "not item.path|regex_search('\\.frep$|conf.d')"
- name: Copy files
  copy:
    src: '{{ item.src }}'
    dest: "{{huginn_hostdir}}/{{ item.path }}"
    mode: '{{ item.mode }}'
  with_filetree: "{{huginn_code_dir}}/setup/"
  when:
  - "item.state == 'file'"
  - "item.path|regex_search('\\.frep$|conf.d')"
- blockinfile:
    create: true
    path: "{{huginn_hostdir}}/.env"
    content: |-
      {{huginn_dotenv}}
      {{huginn_dotenv_extra}}
    marker: "# ANSIBLE MANAGED BLOCK :: deploy commit :: {mark}"
